root: true

parser: "@typescript-eslint/parser"

plugins:
  - "@typescript-eslint"
  - prettier

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended

rules:
  prettier/prettier: error

parserOptions:
  ecmaVersion: 2018
  project: "./tsconfig.json"
  sourceType: module

env:
  browser: true

globals:
  $: true

ignorePatterns:
  - "*.config.js"
